### ISSUE TITLE
 nti.site.runner._RunJobInSite.describe_transaction needs to return unicode

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.site#14]
Since transaction 2.0.3 requires unicode for the user and description fields, we want to make sure that  nti.site.runner._RunJobInSite.describe_transaction return a unicode string when a job name is not specified.

Thanks 

Carlos

**Comment by jamadden** [comment]
This can and should be done in a way compatible with transaction 1, too,  where those strings should be bytes. Additionally, there is a lurking bug under transaction 1 and Python 3 that could result in UnicodeError when a zodb storage gets ahold of it.

**Comment by papachoco** [comment]
Fix is good

**Comment by jamadden** [comment]
Can you use the `Review` button on PR #15 itself to approve the changes?

**Comment by jamadden** [comment]
(It's on the Files Changed tab if you haven't seen it.)
