### ISSUE TITLE
HostSitesFolder lastSynchronized attribute not updated on synchronize_host_policies()

### ISSUE THREAD

**Issue by shsmith5595** [NextThought/nti.site#24]
I am not seeing a `HostSitesFolder` object's `lastSynchronized` attribute updated after `synchronize_host_policies()` is called. It appears that it remains unchanged after it's default value is set to 0 upon initialization and I cannot find references elsewhere in the project that update it. Is this attribute expected to change when `synchronize_host_policies()` is called?

**Comment by jamadden** [comment]
So far, that has been the responsibility of the *caller* to update. There are a number of cases where this package doesn't have the full details and would alter values indiscriminately.

**Comment by shsmith5595** [comment]
Ah, makes sense. Thanks for the clarification.
