### ISSUE TITLE
Remove HostPolicySiteManager.subscribedRegisterUtility/subscribeUnregisterUtility

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.site#5]
They are almost exact copies of the superclass except they leave out the correct policy for when to register the subscriber. This is a bug, not a feature.

Unregistering can silently leave the components in a bad (inconsistent) state when the force parameter is true. The correct thing to do is to fix the components manually.

**Comment by jamadden** [comment]
These functions are also completely untested and they have enough branches that I *really* don't want to try to write test cases for them.

@papachoco unless you object I will plan to remove these for 1.0.

**Comment by papachoco** [comment]
It's OK. Thanks for catching the error. The reason I coded it as such b/c it was very slow to register any component. Specially when unregistering/registering assessment objects.  Checking the subscriber is slow
